### ISSUE TITLE
Error with conversion- Missing mdf2 file

### ISSUE THREAD

**Issue by choiik121** [keegars/MHR-Model-Converter#1]
Hi. I was trying to convert the attached mod, but I was getting an error in the leg mesh file because the corresponding mdf2 file does not exist. I could not apply the manual fix method either. How should I fix this?

[Yae_Sakura.zip](https://github.com/keegars/MHR-Model-Converter/files/9031192/Yae_Sakura.zip)

**Comment by keegars** [comment]
Does the leg mesh use the pl279 mdf2 file? If so, you can extract the mdf2 from the the rise pak file using the mhrisePC.list found on the mh rise modding github and the retool. Open it with the mdf manager, find the materials and update them via that method.

**Comment by choiik121** [comment]
I tried it but the mdf2 from original game doesn't seem compatible with the mod file. Any other things that I might try out?

**Comment by keegars** [comment]
Ah I see your issue now, you are missing an MDF2 for the mod, specifically the one for the leg. Without it you won't be able to convert it properly. You may need to contact whoever you got that mod from.
